# Generated by Django 5.2 on 2025-12-12 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=5, unique=True, verbose_name='Immatriculation')),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Longueur (m)')),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Envergure/Largeur (m)')),
                ('type', models.CharField(max_length=4, verbose_name='Type (Ex: B737)')),
                ('description', models.CharField(max_length=255, verbose_name="Description de l'avion")),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_operationnel', models.CharField(max_length=10, unique=True)),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_stand_aerogare', models.IntegerField()),
                ('disponibilite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name="Description de l'Incident")),
                ('type_incident', models.CharField(max_length=50, verbose_name='Type (Ex: Panne Électrique)')),
                ('date_heure_declaration', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure de Déclaration')),
                ('date_heure_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure de Résolution')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('ENCOURS', 'En Cours de Résolution'), ('RESOLU', 'Résolu')], default='OUVERT', max_length=10, verbose_name='Statut')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_rapportes', to='ManagePark.stand', verbose_name='Stand Affecté')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_vol_arrive', models.CharField(max_length=10, unique=True, verbose_name='Numéro de Vol Arrivée')),
                ('num_vol_depart', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de Vol Départ')),
                ('date_heure_debut_occupation', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('date_heure_fin_occupation', models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('provenance', models.CharField(max_length=100, verbose_name='Ville/Aéroport de Provenance')),
                ('destination', models.CharField(max_length=100, verbose_name='Ville/Aéroport de Destination')),
                ('statut', models.CharField(choices=[('ATTENTE', "En Attente d'Allocation"), ('ALLOUE', 'Alloué à un Stand')], default='ATTENTE', max_length=10, verbose_name="Statut d'Allocation")),
                ('avion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vols_effectues', to='ManagePark.avion', verbose_name='Avion du vol')),
                ('stand_alloue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vols_alloues', to='ManagePark.stand')),
            ],
        ),
    ]
