# Generated by Django 5.2 on 2025-12-14 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagePark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique_allocations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_vol_arrive', models.CharField()),
                ('num_vol_depart', models.CharField()),
                ('date_heure_debut_occupation', models.DateTimeField(null=True)),
                ('date_heure_fin_occupation', models.DateTimeField(null=True)),
                ('provenance', models.CharField()),
                ('destination_apres_atterissage', models.CharField()),
                ('stand_alloue', models.CharField()),
                ('immatriculation_avion', models.CharField()),
                ('type_avion', models.CharField()),
                ('description_avion', models.CharField()),
            ],
        ),
    ]
