# Generated by Django 5.1.6 on 2025-12-14 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagePark', '0002_historique_allocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_rapportes', to='ManagePark.stand', verbose_name='Parking Affecté'),
        ),
    ]
