# Generated by Django 5.1.6 on 2025-12-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagePark', '0003_alter_incident_stand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(max_length=255, verbose_name='Type (Ex: Panne Électrique)'),
        ),
    ]
